# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
# Mod properties
mod.version=0.10.0
mod.group=dev.coder2195.stellarity
mod.id=stellarity
mod.name=Stellarity Enlightened
# Global dependencies
deps.fabric_loader=0.19.5
publish.modrinth=45WspQ04
publish.curseforge=1589190