# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
# Mod properties
mod.version=0.10.0
mod.group=dev.coder2195.stellarity
mod.id=stellarity
mod.name=Stellarity Enlightened
# Global dependencies
deps.fabric_loader=0.19.5
publish.modrinth=45WspQ04
publish.curseforge=1589190

deps.fabric_api=0.159.3+26.3
deps.biolith=3.7.0-alpha.2
deps.modonomicon=26.2-2.2.0
deps.minecraft_dev=26.3-pre-1
# Minecraft dependency for fabric.mod.json
mod.mc_dep=>=26.3- <26.4
# Release title for Modrinth and Curseforge
mod.mc_title=26.3
# Space-separated compatible versions for publishing
mod.mc_targets=26.3