package dev.coder2195.stellarity.datagen.tags;

import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagsProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.TagBuilder;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.trading.VillagerTrade;

import java.util.concurrent.CompletableFuture;

import static dev.coder2195.stellarity.registry.StellarityVillagerTrades.*;
import static dev.coder2195.stellarity.tags.StellarityVillagerTradeTags.*;

public class VillagerTradeTagProvider extends FabricTagsProvider<VillagerTrade> {
	public VillagerTradeTagProvider(FabricPackOutput output, CompletableFuture<HolderLookup.Provider> registryLookupFuture) {
		super(output, Registries.VILLAGER_TRADE, registryLookupFuture);
	}

	@SafeVarargs
	private TagBuilder addTags(TagKey<VillagerTrade> tag, ResourceKey<VillagerTrade>... trades) {
		var builder = getOrCreateRawBuilder(tag);
		for (var trade : trades) {
			builder.addElement(trade.identifier());
		}
		return builder;
	}

	@SuppressWarnings("DuplicatedCode")
	@Override
	protected void addTags(HolderLookup.Provider provider) {
		addTags(ARMORER_LEVEL_1, ARMORER_1_COAL_ENDERITE_SHARD, ARMORER_1_CHARCOAL_ENDERITE_SHARD, ARMORER_1_BLAZE_ROD_ENDERITE_SHARD);
		addTags(ARMORER_LEVEL_1_2, ARMORER_1_ENDERITE_SHARD_IRON_CHESTPLATE, ARMORER_1_ENDERITE_SHARD_IRON_HELMET);
		addTags(ARMORER_LEVEL_2, ARMORER_2_ENDERITE_SHARD_IRON_LEGGINGS, ARMORER_2_ENDERITE_SHARD_IRON_BOOTS);
		addTags(ARMORER_LEVEL_2_2, ARMORER_2_ENDERITE_SHARD_HALLOWED_INGOT, ARMORER_2_ENDERITE_SHARD_CHORUS_PLATING);
		addTags(ARMORER_LEVEL_3, ARMORER_3_DIAMOND_ENDERITE_SHARD, ARMORER_3_ENDERITE_SHARD_SHIELD_COPPER_ELEKTRA_SHIELD);
		addTags(ARMORER_LEVEL_4, ARMORER_4_PURPUR_BLOCK_ENDERITE_SHARD_ENDERITE_UPGRADE_SMITHING_TEMPLATE, ARMORER_4_ENDERITE_SHARD_DIAMOND_LEGGINGS, ARMORER_4_ENDERITE_SHARD_DIAMOND_BOOTS);
		addTags(ARMORER_LEVEL_5, ARMORER_5_ENDERITE_SHARD_DIAMOND_CHESTPLATE, ARMORER_5_ENDERITE_SHARD_DIAMOND_HELMET);

		addTags(BUTCHER_LEVEL_1, BUTCHER_1_ENDERMAN_FLESH_ENDERITE_SHARD, BUTCHER_1_PHANTOM_MEMBRANE_ENDERITE_SHARD);
		addTags(BUTCHER_LEVEL_2, BUTCHER_2_COAL_ENDERITE_SHARD, BUTCHER_2_CHARCOAL_ENDERITE_SHARD);
		addTags(BUTCHER_LEVEL_2_2, BUTCHER_2_ENDERMAN_FLESH_ENDERITE_SHARD_FROZEN_CARPACCIO, BUTCHER_2_ENDERMAN_FLESH_ENDERITE_SHARD_GRILLED_ENDERMAN_FLESH);
		addTags(BUTCHER_LEVEL_3, BUTCHER_3_SHULKER_BODY_ENDERITE_SHARD, BUTCHER_3_ENDERITE_SHARD_SHULKER_BODY);
		addTags(BUTCHER_LEVEL_3_2, BUTCHER_3_ENDERITE_SHARD_IRON_AXE);
		addTags(BUTCHER_LEVEL_4, BUTCHER_4_BEEF_LEATHER_ENDERITE_SHARD, BUTCHER_4_MUTTON_WOOL_ENDERITE_SHARD, BUTCHER_4_CHICKEN_FEATHER_ENDERITE_SHARD, BUTCHER_4_PORKCHOP_ENDERITE_SHARD);
		addTags(BUTCHER_LEVEL_4_2, BUTCHER_4_ENDERITE_SHARD_PHO);
		addTags(BUTCHER_LEVEL_5, BUTCHER_5_ENDERITE_SHARD_SHEPHERDS_PIE, BUTCHER_5_ENDERITE_SHARD_DRIED_KELP_BLOCK);

		addTags(CARTOGRAPHER_LEVEL_1, CARTOGRAPHER_1_PAPER_ENDERITE_SHARD, CARTOGRAPHER_1_ENDERITE_SHARD_MAP);
		addTags(CARTOGRAPHER_LEVEL_2, CARTOGRAPHER_2_GLASS_PANE_ENDERITE_SHARD, CARTOGRAPHER_2_MAP_ENDERITE_SHARD_END_CITY_EXPLORER_MAP);
		addTags(CARTOGRAPHER_LEVEL_3, CARTOGRAPHER_3_ENDERITE_SHARD_ITEM_FRAME, CARTOGRAPHER_3_MAP_ENDERITE_SHARD_CHAPEL_OF_LIGHT_MAP);
		addTags(CARTOGRAPHER_LEVEL_4, CARTOGRAPHER_4_ENDERITE_SHARD_GLOW_ITEM_FRAME, CARTOGRAPHER_4_ENDERITE_SHARD_PHANTOM_ITEM_FRAME);
		addTags(CARTOGRAPHER_LEVEL_5, CARTOGRAPHER_5_ENDERITE_SHARD_MOJANG_BANNER_PATTERN);

		addTags(CLERIC_LEVEL_1, CLERIC_1_PHANTOM_MEMBRANE_ENDERITE_SHARD, CLERIC_1_BONE_ENDERITE_SHARD, CLERIC_1_ENDERMANS_HAND_ENDERITE_SHARD);
		addTags(CLERIC_LEVEL_1_2, CLERIC_1_ENDERITE_SHARD_REDSTONE, CLERIC_1_ENDERITE_SHARD_BLAZE_ROD);
		addTags(CLERIC_LEVEL_2, CLERIC_2_GOLD_INGOT_ENDERITE_SHARD);
		addTags(CLERIC_LEVEL_2_2, CLERIC_2_ENDERITE_SHARD_LAPIS_LAZULI, CLERIC_2_ENDERITE_SHARD_NETHER_WART);
		addTags(CLERIC_LEVEL_3, CLERIC_3_ENDERITE_SHARD_LEVEL_3_POTION, CLERIC_3_ENDERITE_SHARD_GLOWSTONE);
		addTags(CLERIC_LEVEL_4, CLERIC_4_ENDER_PEARL_ENDERITE_SHARD, CLERIC_4_ENDERITE_SHARD_LEVEL_4_POTION);
		addTags(CLERIC_LEVEL_5, CLERIC_5_ENDERITE_SHARD_LEVEL_5_POTION, CLERIC_5_DRAGONS_BREATH_ENDERITE_SHARD);

		addTags(FARMER_LEVEL_1, FARMER_1_WHEAT_ENDERITE_SHARD, FARMER_1_POTATO_ENDERITE_SHARD, FARMER_1_CARROT_ENDERITE_SHARD, FARMER_1_BEETROOT_ENDERITE_SHARD);
		addTags(FARMER_LEVEL_1_2, FARMER_1_ENDERITE_SHARD_BREAD, FARMER_1_ENDERITE_SHARD_CAKE);
		addTags(FARMER_LEVEL_2, FARMER_2_CHORUS_FRUIT_ENDERITE_SHARD, FARMER_2_CHORUS_FLOWER_ENDERITE_SHARD);
		addTags(FARMER_LEVEL_2_2, FARMER_2_ENDERITE_SHARD_CHORUS_PIE, FARMER_2_ENDERITE_SHARD_SHROOMLIGHT);
		addTags(FARMER_LEVEL_3, FARMER_3_ENDERITE_SHARD_CANDIED_CHORUS_FRUIT);
		addTags(FARMER_LEVEL_3_2, FARMER_3_WHEAT_SEEDS_ENDERITE_SHARD_TORCHFLOWER_SEEDS, FARMER_3_WHEAT_SEEDS_ENDERITE_SHARD_PITCHER_POD);
		addTags(FARMER_LEVEL_4, FARMER_4_ENDERITE_SHARD_CHORUS_JUICE, FARMER_4_ENDERITE_SHARD_CHORUS_STEW);
		addTags(FARMER_LEVEL_4_2, FARMER_4_ENDERITE_SHARD_FRIED_CHORUS_FRUIT);
		addTags(FARMER_LEVEL_5, FARMER_5_ENDERITE_SHARD_PHO, FARMER_5_BREAD_ENDERITE_SHARD_LOAF_OF_PLENTY);

		addTags(FISHERMAN_LEVEL_1, FISHERMAN_1_FISHING_ROD_ENDERITE_SHARD, FISHERMAN_1_ENDERITE_SHARD_FISHING_ROD);
		addTags(FISHERMAN_LEVEL_1_2, FISHERMAN_1_STRING_ENDERITE_SHARD, FISHERMAN_1_COAL_ENDERITE_SHARD);
		addTags(FISHERMAN_LEVEL_2, FISHERMAN_2_ENDER_KOI_ENDERITE_SHARD, FISHERMAN_2_OVERGROWN_COD_ENDERITE_SHARD, FISHERMAN_2_FROST_MINNOW_ENDERITE_SHARD, FISHERMAN_2_GOOSH_ENDERITE_SHARD);
		addTags(FISHERMAN_LEVEL_2_2, FISHERMAN_2_ENDERITE_SHARD_CAMPFIRE, FISHERMAN_2_ENDERITE_SHARD_SOUL_CAMPFIRE);
		addTags(FISHERMAN_LEVEL_3, FISHERMAN_3_ENDERITE_SHARD_FISHING_ROD);
		addTags(FISHERMAN_LEVEL_3_2, FISHERMAN_3_CRIMSON_TIGERFISH_ENDERITE_SHARD, FISHERMAN_3_FLESHY_PIRANHA_ENDERITE_SHARD, FISHERMAN_3_FLAREFIN_KOI_ENDERITE_SHARD, FISHERMAN_3_POTASSIFISH_ENDERITE_SHARD);
		addTags(FISHERMAN_LEVEL_4, FISHERMAN_4_ENDERITE_SHARD_LURE_BOOK, FISHERMAN_4_ENDERITE_SHARD_LUCK_OF_THE_SEA_BOOK);
		addTags(FISHERMAN_LEVEL_4_2, FISHERMAN_4_ENDERITE_SHARD_FISHER_OF_VOIDS);
		addTags(FISHERMAN_LEVEL_5, FISHERMAN_5_CRYSTAL_HEARTFISH_ENDERITE_SHARD, FISHERMAN_5_ENDERITE_SHARD_PRISMATIC_SUSHI);

		addTags(FLETCHER_LEVEL_1, FLETCHER_1_ENDERITE_SHARD_SPECTRAL_ARROW, FLETCHER_1_ENDERITE_SHARD_ARROW);
		addTags(FLETCHER_LEVEL_1_2, FLETCHER_1_STICK_ENDERITE_SHARD);
		addTags(FLETCHER_LEVEL_2, FLETCHER_2_FLINT_ENDERITE_SHARD, FLETCHER_2_ENDERITE_SHARD_BOW);
		addTags(FLETCHER_LEVEL_3, FLETCHER_3_STRING_ENDERITE_SHARD, FLETCHER_3_FEATHER_ENDERITE_SHARD, FLETCHER_3_ENDERITE_SHARD_CROSSBOW);
		addTags(FLETCHER_LEVEL_4, FLETCHER_4_ARROW_ENDERITE_SHARD_LEVITATION_TIPPED_ARROW, FLETCHER_4_ARROW_ENDERITE_SHARD_LUCK_TIPPED_ARROW);
		addTags(FLETCHER_LEVEL_5, FLETCHER_5_BOW_ENDERITE_SHARD_SHARANGA);

		addTags(LEATHERWORKER_LEVEL_1, LEATHERWORKER_1_LEATHER_ENDERITE_SHARD, LEATHERWORKER_1_FLINT_ENDERITE_SHARD);
		addTags(LEATHERWORKER_LEVEL_2, LEATHERWORKER_2_ENDERITE_SHARD_SADDLE, LEATHERWORKER_2_ENDERITE_SHARD_LEATHER);
		addTags(LEATHERWORKER_LEVEL_3, LEATHERWORKER_3_ENDERITE_SHARD_CAULDRON, LEATHERWORKER_3_RABBIT_HIDE_ENDERITE_SHARD);
		addTags(LEATHERWORKER_LEVEL_4, LEATHERWORKER_4_ITEM_FRAME_ENDERITE_SHARD_GLOW_ITEM_FRAME);
		addTags(LEATHERWORKER_LEVEL_4_2, LEATHERWORKER_4_ENDERITE_SHARD_TURTLE_SCUTE, LEATHERWORKER_4_ENDERITE_SHARD_ARMADILLO_SCUTE);
		addTags(LEATHERWORKER_LEVEL_5, LEATHERWORKER_5_DIAMOND_HORSE_ARMOR_ENDERITE_SHARD_REINFORCED_HORSE_ARMOR);

		addTags(LIBRARIAN_LEVEL_1, LIBRARIAN_1_PAPER_ENDERITE_SHARD, LIBRARIAN_1_BOOK_ENDERITE_SHARD);
		addTags(LIBRARIAN_LEVEL_1_2, LIBRARIAN_1_ENDERITE_SHARD_BOOKSHELF, LIBRARIAN_1_BOOK_ENDERITE_SHARD_LEVEL_1_ENCHANTED_BOOK);
		addTags(LIBRARIAN_LEVEL_2, LIBRARIAN_2_ENDERITE_SHARD_LANTERN, LIBRARIAN_2_BOOK_ENDERITE_SHARD_LEVEL_2_ENCHANTED_BOOK);
		addTags(LIBRARIAN_LEVEL_3, LIBRARIAN_3_ENDERITE_SHARD_INK_SAC, LIBRARIAN_3_ENDERITE_SHARD_GLOW_INK_SAC);
		addTags(LIBRARIAN_LEVEL_3_2, LIBRARIAN_3_ENDERITE_SHARD_GLASS);
		addTags(LIBRARIAN_LEVEL_4, LIBRARIAN_4_BOOK_ENDERITE_SHARD_LEVEL_4_ENCHANTED_BOOK, LIBRARIAN_4_ENDERITE_SHARD_WRITABLE_BOOK);
		addTags(LIBRARIAN_LEVEL_4_2, LIBRARIAN_4_ENDERITE_SHARD_NAME_TAG);
		addTags(LIBRARIAN_LEVEL_5, LIBRARIAN_5_BOOK_ENDERITE_SHARD_BOOK_OF_OBSTRUCT, LIBRARIAN_5_BOOK_ENDERITE_SHARD_BOOK_OF_LIGHT, LIBRARIAN_5_BOOK_ENDERITE_SHARD_BOOK_OF_UPDRAFT);

		addTags(MASON_LEVEL_1, MASON_1_ENDERITE_SHARD_PURPUR_BLOCK, MASON_1_ENDERITE_SHARD_END_STONE_BRICKS);
		addTags(MASON_LEVEL_2, MASON_2_AMETHYST_BUDFISH_AMETHYST_SHARD, MASON_2_AMETHYST_BUDFISH_QUARTZ);
		addTags(MASON_LEVEL_2_2, MASON_2_ENDERITE_SHARD_OBSIDIAN, MASON_2_ENDERITE_SHARD_SMOOTH_QUARTZ);
		addTags(MASON_LEVEL_3, MASON_3_ENDERITE_SHARD_POLISHED_BLACKSTONE, MASON_3_ENDERITE_SHARD_POLISHED_DEEPSLATE, MASON_3_COBBLED_DEEPSLATE_ENDERITE_SHARD, MASON_3_BLACKSTONE_ENDERITE_SHARD);
		addTags(MASON_LEVEL_3_2, MASON_3_ENDERITE_SHARD_QUARTZ_BLOCK, MASON_3_ENDERITE_SHARD_QUARTZ_PILLAR);
		var mason4 = addTags(MASON_LEVEL_4);
		MASON_4_ENDERITE_SHARD_GLAZED_TERRACOTA.forEach(trade -> mason4.addElement(trade.identifier()));
		var mason42 = addTags(MASON_LEVEL_4_2);
		MASON_4_ENDERITE_SHARD_TERRACOTA.forEach(trade -> mason42.addElement(trade.identifier()));
		addTags(MASON_LEVEL_5, MASON_5_ENDERITE_SHARD_CRYING_OBSIDIAN);
		addTags(MASON_LEVEL_5_2, MASON_5_ENDERITE_SHARD_PURPUR_PILLAR, MASON_5_ENDERITE_SHARD_CHISELED_QUARTZ_BLOCK);

		addTags(SHEPHERD_LEVEL_1, SHEPHERD_1_ENDERITE_SHARD_SHEARS, SHEPHERD_1_WHITE_WOOL_ENDERITE_SHARD);
		var shepherd2 = addTags(SHEPHERD_LEVEL_2);
		SHEPHERD_2_ENDERITE_SHARD_DYE.forEach(trade -> shepherd2.addElement(trade.identifier()));
		var shepherd22 = addTags(SHEPHERD_LEVEL_2_2);
		SHEPHERD_2_ENDERITE_SHARD_WOOL.forEach(trade -> shepherd22.addElement(trade.identifier()));
		var shepherd3 = addTags(SHEPHERD_LEVEL_3);
		SHEPHERD_3_ENDERITE_SHARD_CARPET.forEach(trade -> shepherd3.addElement(trade.identifier()));
		var shepherd32 = addTags(SHEPHERD_LEVEL_3_2);
		SHEPHERD_3_ENDERITE_SHARD_WOOL.forEach(trade -> shepherd32.addElement(trade.identifier()));
		var shepherd33 = addTags(SHEPHERD_LEVEL_3_3);
		SHEPHERD_3_ENDERITE_SHARD_BED.forEach(trade -> shepherd33.addElement(trade.identifier()));
		var shepherd4 = addTags(SHEPHERD_LEVEL_4);
		SHEPHERD_4_ENDERITE_SHARD_BANNER.forEach(trade -> shepherd4.addElement(trade.identifier()));
		var shepherd42 = addTags(SHEPHERD_LEVEL_4_2);
		SHEPHERD_4_ENDERITE_SHARD_WOOL.forEach(trade -> shepherd42.addElement(trade.identifier()));
		var shepherd43 = addTags(SHEPHERD_LEVEL_4_3);
		SHEPHERD_4_ENDERITE_SHARD_DYE.forEach(trade -> shepherd43.addElement(trade.identifier()));
		addTags(SHEPHERD_LEVEL_5, SHEPHERD_5_ENDERITE_SHARD_FIRE_PAINTING, SHEPHERD_5_ENDERITE_SHARD_WIND_PAINTING, SHEPHERD_5_ENDERITE_SHARD_EARTH_PAINTING, SHEPHERD_5_ENDERITE_SHARD_WATER_PAINTING);
		addTags(SHEPHERD_LEVEL_5_2, SHEPHERD_5_ENDERITE_SHARD_A_HOP_AND_A_SKIP_AWAY_PAINTING, SHEPHERD_5_ENDERITE_SHARD_DRAGONBLADE_PAINTING, SHEPHERD_5_ENDERITE_SHARD_END_PAINTING, SHEPHERD_5_ENDERITE_SHARD_END_BLOSSOM_PAINTING, SHEPHERD_5_ENDERITE_SHARD_HOURGLASS_PAINTING, SHEPHERD_5_ENDERITE_SHARD_MAJESTICAL_BREW_PAINTING, SHEPHERD_5_ENDERITE_SHARD_SCHEME_PAINTING, SHEPHERD_5_ENDERITE_SHARD_SHEPHERDS_FEAST_PAINTING, SHEPHERD_5_ENDERITE_SHARD_SNARE_PAINTING, SHEPHERD_5_ENDERITE_SHARD_SNATCH_PAINTING, SHEPHERD_5_ENDERITE_SHARD_THE_OBSIDIAN_RELIQUARY_PAINTING);

		addTags(TOOLSMITH_LEVEL_1, TOOLSMITH_1_COAL_ENDERITE_SHARD, TOOLSMITH_1_CHARCOAL_ENDERITE_SHARD, TOOLSMITH_1_BLAZE_ROD_ENDERITE_SHARD);
		addTags(TOOLSMITH_LEVEL_1_2, TOOLSMITH_1_ENDERITE_SHARD_IRON_HOE, TOOLSMITH_1_ENDERITE_SHARD_IRON_SHOVEL);
		addTags(TOOLSMITH_LEVEL_2, TOOLSMITH_2_ENDERITE_SHARD_IRON_AXE, TOOLSMITH_2_ENDERITE_SHARD_IRON_PICKAXE);
		addTags(TOOLSMITH_LEVEL_2_2, TOOLSMITH_2_ENDERITE_SHARD_HALLOWED_INGOT, TOOLSMITH_2_ENDERITE_SHARD_CHORUS_PLATING);
		addTags(TOOLSMITH_LEVEL_3, TOOLSMITH_3_DIAMOND_ENDERITE_SHARD, TOOLSMITH_3_BOOK_ENDERITE_SHARD_LEVEL_3_ENCHANTED_BOOK);
		addTags(TOOLSMITH_LEVEL_4, TOOLSMITH_4_PURPUR_BLOCK_ENDERITE_SHARD_ENDERITE_UPGRADE_SMITHING_TEMPLATE);
		addTags(TOOLSMITH_LEVEL_4_2, TOOLSMITH_4_ENDERITE_SHARD_DIAMOND_HOE, TOOLSMITH_4_ENDERITE_SHARD_DIAMOND_SHOVEL);
		addTags(TOOLSMITH_LEVEL_5, TOOLSMITH_5_ENDERITE_SHARD_DIAMOND_AXE, TOOLSMITH_5_ENDERITE_SHARD_DIAMOND_PICKAXE);

		addTags(WEAPONSMITH_LEVEL_1, WEAPONSMITH_1_COAL_ENDERITE_SHARD, WEAPONSMITH_1_CHARCOAL_ENDERITE_SHARD, WEAPONSMITH_1_BLAZE_ROD_ENDERITE_SHARD);
		addTags(WEAPONSMITH_LEVEL_1_2, WEAPONSMITH_1_ENDERITE_SHARD_IRON_SWORD);
		addTags(WEAPONSMITH_LEVEL_2, WEAPONSMITH_2_ENDERITE_SHARD_IRON_AXE);
		addTags(WEAPONSMITH_LEVEL_2_2, WEAPONSMITH_2_ENDERITE_SHARD_HALLOWED_INGOT, WEAPONSMITH_2_ENDERITE_SHARD_CHORUS_PLATING);
		addTags(WEAPONSMITH_LEVEL_3, WEAPONSMITH_3_BOOK_ENDERITE_SHARD_LEVEL_3_ENCHANTED_BOOK, WEAPONSMITH_3_DIAMOND_ENDERITE_SHARD);
		addTags(WEAPONSMITH_LEVEL_4, WEAPONSMITH_4_ENDERITE_SHARD_DIAMOND_SWORD, WEAPONSMITH_4_PURPUR_BLOCK_ENDERITE_SHARD_ENDERITE_UPGRADE_SMITHING_TEMPLATE);
		addTags(WEAPONSMITH_LEVEL_5, WEAPONSMITH_5_ENDERITE_SHARD_DIAMOND_AXE, WEAPONSMITH_5_GOLDEN_SWORD_ENDERITE_SHARD_STELLAR_STRIKER);
	}
}
